## Numpy

In [2]:
import numpy as np

In [4]:
#Create an array called array1 from the given list.
lst = [10, 20, 30]
print(lst)
array1 = np.array(lst)
array1

[10, 20, 30]


array([10, 20, 30])

In [5]:
print(type(array1))

<class 'numpy.ndarray'>


In [8]:
## dimention
array1.ndim

1

In [11]:
## shape
array1.shape

(3,)

In [14]:
## size
array1.size

3

In [16]:
## data type
array1.dtype

dtype('int32')

In [18]:
## ietem size - size of each item 32bit => 32/8 = 4 byte
array1.itemsize

4

In [6]:
array2 = np.array([[1,2,4], [4, 7, 2], [9, 4, 7]])
array2

array([[1, 2, 4],
       [4, 7, 2],
       [9, 4, 7]])

In [7]:
type(array2)

numpy.ndarray

In [10]:
## dimention
array2.ndim

2

In [13]:
## shape
array2.shape

(3, 3)

In [15]:
## size
array2.size

9

In [17]:
## data type
array2.dtype

dtype('int32')

In [19]:
## ietem size - size of each item 32bit => 32/8 = 4 byte
array2.itemsize

4

In [21]:
# 1. ## define with data type - 
array1 = np.array([10, 20, 30], dtype = float)
array1

array([10., 20., 30.])

In [22]:
array1.dtype

dtype('float64')

In [23]:
# 2. with np.zeros, ## float data type
array1 = np.zeros((3,4))
array1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
# 3. with np.ones  ## float data type
array1 = np.ones((3,4))
array1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
# 4. with np.arange  ## float data type
array1 = np.arange(6)
array1

array([0, 1, 2, 3, 4, 5])

In [28]:
array1 = np.arange(3, 10)
array1

array([3, 4, 5, 6, 7, 8, 9])

In [29]:
## indexing 
array1 = np.arange(3, 10)
array1

array([3, 4, 5, 6, 7, 8, 9])

In [30]:
array1[0] ## similar to list 

3

In [31]:
array2 = np.array([[1,2,4], [4, 7, 2], [9, 4, 7]])
array2

array([[1, 2, 4],
       [4, 7, 2],
       [9, 4, 7]])

In [33]:
array2[1, 2]  ## for 2d array

2

In [34]:
## Slicing : form start ton end - 1 
array1[3:5]

array([6, 7])

In [37]:
array2 = np.array([[1,2,4, 6, 3], [4, 7, 2, 5, 0], [9, 4, 7, 6, 10], [1, 7, 2, 9, 5], [4, 6, 2, 7, 9]])
array2


array([[ 1,  2,  4,  6,  3],
       [ 4,  7,  2,  5,  0],
       [ 9,  4,  7,  6, 10],
       [ 1,  7,  2,  9,  5],
       [ 4,  6,  2,  7,  9]])

In [38]:
array2[1:3, 2:5]

array([[ 2,  5,  0],
       [ 7,  6, 10]])

In [39]:
array1 = np.array([[1,2], [4, 7]])
array2 = np.array([[10,5], [3, 4]])
array1 + array2

array([[11,  7],
       [ 7, 11]])

In [ ]:
## matrix multiplication
# [[1, 2]  # [[10, 5]
# [4, 7]] # [3, 4]]

[
    [1 x 10 + 2 x 3     1 x 5 + 2 x 4]
    [4 x 10 + 7 x 3     4 x 5 + 7 x 4]
]
    

In [40]:
array1 @ array2

array([[16, 13],
       [61, 48]])

In [41]:
array1 ** 3

array([[  1,   8],
       [ 64, 343]], dtype=int32)

In [42]:
array2/array1

array([[10.        ,  2.5       ],
       [ 0.75      ,  0.57142857]])

In [43]:
array2 % array1

array([[0, 1],
       [3, 4]])

In [44]:
array2 = np.array([[1,2,4, 6, 3], [4, 7, 2, 5, 0], [9, 4, 7, 6, 10], [1, 7, 2, 9, 5], [4, 6, 2, 7, 9]])
array2

array([[ 1,  2,  4,  6,  3],
       [ 4,  7,  2,  5,  0],
       [ 9,  4,  7,  6, 10],
       [ 1,  7,  2,  9,  5],
       [ 4,  6,  2,  7,  9]])

In [46]:
array2.transpose()  ## do not alter original array

array([[ 1,  4,  9,  1,  4],
       [ 2,  7,  4,  7,  6],
       [ 4,  2,  7,  2,  2],
       [ 6,  5,  6,  9,  7],
       [ 3,  0, 10,  5,  9]])

In [47]:
array2

array([[ 1,  2,  4,  6,  3],
       [ 4,  7,  2,  5,  0],
       [ 9,  4,  7,  6, 10],
       [ 1,  7,  2,  9,  5],
       [ 4,  6,  2,  7,  9]])

In [54]:
array1 = np.array([[5,2], [10, 7]])
# array2 = np.array([[10,5], [3, 4]])
array1.sort()

In [55]:
array1

array([[ 2,  5],
       [ 7, 10]])

In [56]:
array2 = np.array([[1,2,4, 6, 3], [4, 7, 2, 5, 0], [9, 4, 7, 6, 10], [1, 7, 2, 9, 5], [4, 6, 2, 7, 9]])
array2

array([[ 1,  2,  4,  6,  3],
       [ 4,  7,  2,  5,  0],
       [ 9,  4,  7,  6, 10],
       [ 1,  7,  2,  9,  5],
       [ 4,  6,  2,  7,  9]])

In [58]:
## sort
array2.sort(axis = 1) ## row
array2

array([[ 1,  2,  3,  4,  6],
       [ 0,  2,  4,  5,  7],
       [ 4,  6,  7,  9, 10],
       [ 1,  2,  5,  7,  9],
       [ 2,  4,  6,  7,  9]])

In [59]:
array2.sort(axis = 0) ## columns
array2

array([[ 0,  2,  3,  4,  6],
       [ 1,  2,  4,  5,  7],
       [ 1,  2,  5,  7,  9],
       [ 2,  4,  6,  7,  9],
       [ 4,  6,  7,  9, 10]])

In [64]:
##concatenate
array1 = np.array([[5, 2, 0], [10, 7, 10]])
array2 = np.array([[10,5], [3, 4]])

In [65]:

np.concatenate((array1, array2), axis = 1) ## axis 1 means row

array([[ 5,  2,  0, 10,  5],
       [10,  7, 10,  3,  4]])

In [77]:
array1 = np.arange(3, 18)
array1

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17])

In [78]:
## reshape
array1.reshape(3, 5)

array([[ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17]])

In [73]:
array1.reshape(5, 3)

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [80]:
## reshape
array2 = np.array([[1,2,4, 6, 3], [4, 7, 2, 5, 0], [9, 4, 7, 6, 10], [1, 7, 2, 9, 5]])
array2

array([[ 1,  2,  4,  6,  3],
       [ 4,  7,  2,  5,  0],
       [ 9,  4,  7,  6, 10],
       [ 1,  7,  2,  9,  5]])

In [81]:
array2.reshape(5, 4)

array([[ 1,  2,  4,  6],
       [ 3,  4,  7,  2],
       [ 5,  0,  9,  4],
       [ 7,  6, 10,  1],
       [ 7,  2,  9,  5]])

In [83]:
## split
array2 = np.array([[1,2,4, 6, 3], [4, 7, 2, 5, 0], [9, 4, 7, 6, 10], [1, 7, 2, 9, 5], [4, 6, 2, 7, 9]])
array2

array([[ 1,  2,  4,  6,  3],
       [ 4,  7,  2,  5,  0],
       [ 9,  4,  7,  6, 10],
       [ 1,  7,  2,  9,  5],
       [ 4,  6,  2,  7,  9]])

In [84]:
first, second, third = np.split(array2, [1, 3])

In [85]:
first

array([[1, 2, 4, 6, 3]])

In [86]:
second

array([[ 4,  7,  2,  5,  0],
       [ 9,  4,  7,  6, 10]])

In [87]:
third

array([[1, 7, 2, 9, 5],
       [4, 6, 2, 7, 9]])

In [88]:
## mean
array1 = np.array([[5,2], [10, 7]])
array1.mean()

6.0

In [90]:
## standard deviation
array1 = np.array([[5,2], [10, 7]])
array1.std()

2.9154759474226504

In [91]:
## read array from a file,
studentdata = np.loadtxt(r'C:\Users\atalb\Documents\Python training notebooks/marksheet.txt', skiprows=1, delimiter=',', dtype = int)
studentdata

array([[ 1, 36, 18, 57],
       [ 2, 22, 23, 45],
       [ 3, 43, 51, 37],
       [ 4, 41, 40, 60],
       [ 5, 13, 18, 37]])

In [96]:
## read array from a file, replace no value to nan 
studentdata = np.genfromtxt(r'C:\Users\atalb\Documents\Python training notebooks/marksheet_missing.txt', skip_header = 1, delimiter=',')
studentdata

array([[ 1., 36., 18., 57.],
       [ 2., nan, 23., 45.],
       [ 3., 43., 51., nan],
       [ 4., 41., 40., 60.],
       [ 5., 13., 18., 27.]])

In [98]:
## save array to a file
np.savetxt(r'C:\Users\atalb\Documents\Python training notebooks/save.txt', array2, delimiter=',', fmt='%i')

In [ ]:
4. Create the following NumPy arrays:
a) A 1-D array called zeros having 10 elements and 
all the elements are set to zero.
b) A 1-D array called vowels having the elements ‘a’, 
‘e’, ‘i’, ‘o’ and ‘u’.
c) A 2-D array called ones having 2 rows and 5 
columns and all the elements are set to 1 and 
dtype as int.
d) Use nested Python lists to create a 2-D array called 
myarray1 having 3 rows and 3 columns and store 
the following data:
 2.7, -2, -19
 0, 3.4, 99.9
 10.6, 0, 13
e) A 2-D array called myarray2 using arange() 
having 3 rows and 5 columns with start value = 4, 
step size 4 and dtype as float.